@url = http://localhost:3000

# @name GetStories

GET {{url}}/

###

# @name CreateStory

POST {{url}}/
Content-Type: application/json

{
  "prompt": "Anything",
  "completed": false,
  "turn": 1,
  "frame1": {
        "text": "",
        "img": "",
        "user": "dummyuser"
     }
}

###
